default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rahul
  password: rahul@123
  host: localhost

development:
  <<: *default
  database: airbnb_v2_development

test:
  <<: *default
  database: airbnb_v2_test

production:
  <<: *default
  database: airbnb_v2_production
  username: airbnb_user
  password: <%= ENV['AIRBNB_DATABASE_PASSWORD'] %>
